# Generated by Django 2.2.16 on 2022-12-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221215_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='quantity',
            new_name='amount',
        ),
    ]
