# Generated by Django 2.2.16 on 2023-01-09 07:09

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.check_username], verbose_name='Имя пользователя'),
        ),
    ]
